### ISSUE TITLE
Timings site

### ISSUE THREAD

**Issue by zKoz210** [pmmp/aikar-timings#1]
### Issue description
Warning: Division by zero in /var/www/html/timings/legacy/index.php on line 544

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/28255085/33779993-277b5afa-dc60-11e7-83db-86da844c56c5.png)

**Comment by zKoz210** [comment]
@dktapps You can watch it?

**Comment by dktapps** [comment]
do you have a link for a reproducing timings report?

**Comment by zKoz210** [comment]
@dktapps Sorry for the wait

Ex: https://timings.pmmp.io/?url=26287734

**Comment by dktapps** [comment]
Looks like others I've seen with this bug. The report is truncated, so some information is missing.

**Comment by zKoz210** [comment]
It's weird, I can somehow help to resolve this?

**Comment by Matthww** [comment]
Timings: https://timings.pmmp.io/?url=26316563
Timings report: https://gist.github.com/Matthww/2e6c23b391dd725117eec7b19acfa964

**Comment by dktapps** [comment]
@Matthww yeah, yours is truncated too, look at https://paste.ubuntu.com/26316563/

**Comment by dktapps** [comment]
After doing further tests it appears that Ubuntu Pastebin is corrupting pasted data larger than a certain size. I tested with artificial repeating patterns of fixed lengths and the patterns near the end started getting corrupted.

**Comment by dktapps** [comment]
Update on that: It may be something to do with cURL. Using `file_get_contents()` with a stream context worked fine, no corruptions there.

**Comment by zKoz210** [comment]
@dktapps I did a report within 7 hours after which the data could not load on the site.

"An error happened while pasting the report"

Folder /timings/ was empty

**Comment by dktapps** [comment]
@zKoz210 that is not related to this issue, see https://twitter.com/dktapps/status/962103942539829248

**Comment by dktapps** [comment]
wrt. the truncation issue: https://bugs.php.net/bug.php?id=75597

Please update your PHP to the latest versions provided by PMMP, and try and reproduce the bug again. Thanks.

**Comment by dktapps** [comment]
I am no longer able to reproduce this bug after updating my PHP installation, so I'm going to close this issue.
